// jrtt project jrtt.go
// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package toutiao_ssp_api is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Pmp
	AdSlot
	Publisher
	Content
	App
	Geo
	Device
	Data
	User
	PrivateReq
	BidRequest
	MaterialMeta
	Bid
	SeatBid
	BidResponse
	DspClickNotification
*/
package jrtt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdType int32

const (
	AdType_TOUTIAO_ADTYPE_UNDEFINED     AdType = 0
	AdType_TOUTIAO_FEED_LP_LARGE        AdType = 1
	AdType_TOUTIAO_FEED_LP_SMALL        AdType = 2
	AdType_TOUTIAO_FEED_APP_LARGE       AdType = 4
	AdType_TOUTIAO_FEED_APP_SMALL       AdType = 3
	AdType_TOUTIAO_DETAIL_LP_GRAPHIC    AdType = 5
	AdType_TOUTIAO_DETAIL_LP_BANNER     AdType = 6
	AdType_TUANZI_FEED_APP              AdType = 7
	AdType_TOUTIAO_DETAIL_APP_BANNER    AdType = 9
	AdType_TOUTIAO_DETAIL_LP_TEXT_IMAGE AdType = 10
	AdType_TOUTIAO_FEED_LP_GROUP        AdType = 11
	AdType_TOUTIAO_VIDEO_PATCH          AdType = 12
	AdType_NETWORK_SPLASH               AdType = 13
	AdType_TOUTIAO_SPLASH               AdType = 14
	AdType_DUANZI_FEED_LP_LARGE         AdType = 15
	AdType_DUANZI_FEED_LP_SMALL         AdType = 16
	AdType_DUANZI_FEED_LP_GROUP         AdType = 17
	AdType_TOUTIAO_FEED_APP_GROUP       AdType = 18
	AdType_TOUTIAO_RECOMMEND_LP_SMALL   AdType = 19
)

var AdType_name = map[int32]string{
	0:  "TOUTIAO_ADTYPE_UNDEFINED",
	1:  "TOUTIAO_FEED_LP_LARGE",
	2:  "TOUTIAO_FEED_LP_SMALL",
	4:  "TOUTIAO_FEED_APP_LARGE",
	3:  "TOUTIAO_FEED_APP_SMALL",
	5:  "TOUTIAO_DETAIL_LP_GRAPHIC",
	6:  "TOUTIAO_DETAIL_LP_BANNER",
	7:  "TUANZI_FEED_APP",
	9:  "TOUTIAO_DETAIL_APP_BANNER",
	10: "TOUTIAO_DETAIL_LP_TEXT_IMAGE",
	11: "TOUTIAO_FEED_LP_GROUP",
	12: "TOUTIAO_VIDEO_PATCH",
	13: "NETWORK_SPLASH",
	14: "TOUTIAO_SPLASH",
	15: "DUANZI_FEED_LP_LARGE",
	16: "DUANZI_FEED_LP_SMALL",
	17: "DUANZI_FEED_LP_GROUP",
	18: "TOUTIAO_FEED_APP_GROUP",
	19: "TOUTIAO_RECOMMEND_LP_SMALL",
}
var AdType_value = map[string]int32{
	"TOUTIAO_ADTYPE_UNDEFINED":     0,
	"TOUTIAO_FEED_LP_LARGE":        1,
	"TOUTIAO_FEED_LP_SMALL":        2,
	"TOUTIAO_FEED_APP_LARGE":       4,
	"TOUTIAO_FEED_APP_SMALL":       3,
	"TOUTIAO_DETAIL_LP_GRAPHIC":    5,
	"TOUTIAO_DETAIL_LP_BANNER":     6,
	"TUANZI_FEED_APP":              7,
	"TOUTIAO_DETAIL_APP_BANNER":    9,
	"TOUTIAO_DETAIL_LP_TEXT_IMAGE": 10,
	"TOUTIAO_FEED_LP_GROUP":        11,
	"TOUTIAO_VIDEO_PATCH":          12,
	"NETWORK_SPLASH":               13,
	"TOUTIAO_SPLASH":               14,
	"DUANZI_FEED_LP_LARGE":         15,
	"DUANZI_FEED_LP_SMALL":         16,
	"DUANZI_FEED_LP_GROUP":         17,
	"TOUTIAO_FEED_APP_GROUP":       18,
	"TOUTIAO_RECOMMEND_LP_SMALL":   19,
}

func (x AdType) String() string {
	return proto.EnumName(AdType_name, int32(x))
}
func (AdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AdSlot_Position int32

const (
	AdSlot_UNDEFINED AdSlot_Position = 0
	AdSlot_SPLASH    AdSlot_Position = 1
	AdSlot_FEED      AdSlot_Position = 2
	AdSlot_DETAIL    AdSlot_Position = 4
	AdSlot_RECOMMEND AdSlot_Position = 8
)

var AdSlot_Position_name = map[int32]string{
	0: "UNDEFINED",
	1: "SPLASH",
	2: "FEED",
	4: "DETAIL",
	8: "RECOMMEND",
}
var AdSlot_Position_value = map[string]int32{
	"UNDEFINED": 0,
	"SPLASH":    1,
	"FEED":      2,
	"DETAIL":    4,
	"RECOMMEND": 8,
}

func (x AdSlot_Position) String() string {
	return proto.EnumName(AdSlot_Position_name, int32(x))
}
func (AdSlot_Position) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Device_ConnectionType int32

const (
	Device_CONNECTIONTYPE_UNDEFINED Device_ConnectionType = 0
	Device_Honeycomb                Device_ConnectionType = 1
	Device_WIFI                     Device_ConnectionType = 2
	Device_UNKNOWN                  Device_ConnectionType = 3
	Device_NT_2G                    Device_ConnectionType = 4
	Device_NT_4G                    Device_ConnectionType = 5
)

var Device_ConnectionType_name = map[int32]string{
	0: "CONNECTIONTYPE_UNDEFINED",
	1: "Honeycomb",
	2: "WIFI",
	3: "UNKNOWN",
	4: "NT_2G",
	5: "NT_4G",
}
var Device_ConnectionType_value = map[string]int32{
	"CONNECTIONTYPE_UNDEFINED": 0,
	"Honeycomb":                1,
	"WIFI":                     2,
	"UNKNOWN":                  3,
	"NT_2G":                    4,
	"NT_4G":                    5,
}

func (x Device_ConnectionType) String() string {
	return proto.EnumName(Device_ConnectionType_name, int32(x))
}
func (Device_ConnectionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type Device_DeviceType int32

const (
	Device_DEVICETYPE_UNDEFINED Device_DeviceType = 0
	Device_PHONE                Device_DeviceType = 1
	Device_TABLET               Device_DeviceType = 2
)

var Device_DeviceType_name = map[int32]string{
	0: "DEVICETYPE_UNDEFINED",
	1: "PHONE",
	2: "TABLET",
}
var Device_DeviceType_value = map[string]int32{
	"DEVICETYPE_UNDEFINED": 0,
	"PHONE":                1,
	"TABLET":               2,
}

func (x Device_DeviceType) String() string {
	return proto.EnumName(Device_DeviceType_name, int32(x))
}
func (Device_DeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

type User_Gender int32

const (
	User_GENDER_UNDEFINED User_Gender = 0
	User_MALE             User_Gender = 1
	User_FEMALE           User_Gender = 2
	User_UNKNOWN          User_Gender = 3
)

var User_Gender_name = map[int32]string{
	0: "GENDER_UNDEFINED",
	1: "MALE",
	2: "FEMALE",
	3: "UNKNOWN",
}
var User_Gender_value = map[string]int32{
	"GENDER_UNDEFINED": 0,
	"MALE":             1,
	"FEMALE":           2,
	"UNKNOWN":          3,
}

func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}
func (User_Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type BidRequest_BidReqType int32

const (
	BidRequest_BIDREQTYPE_UNDEFINED BidRequest_BidReqType = 0
	BidRequest_ONLY_RETARGET        BidRequest_BidReqType = 1
	BidRequest_ONLY_DSP             BidRequest_BidReqType = 2
	BidRequest_RETARGET_AND_DSP     BidRequest_BidReqType = 3
)

var BidRequest_BidReqType_name = map[int32]string{
	0: "BIDREQTYPE_UNDEFINED",
	1: "ONLY_RETARGET",
	2: "ONLY_DSP",
	3: "RETARGET_AND_DSP",
}
var BidRequest_BidReqType_value = map[string]int32{
	"BIDREQTYPE_UNDEFINED": 0,
	"ONLY_RETARGET":        1,
	"ONLY_DSP":             2,
	"RETARGET_AND_DSP":     3,
}

func (x BidRequest_BidReqType) String() string {
	return proto.EnumName(BidRequest_BidReqType_name, int32(x))
}
func (BidRequest_BidReqType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

type Bid_BidAdType int32

const (
	Bid_BIDADTYPE_UNDEFINED Bid_BidAdType = 0
	Bid_RETARGET_AD         Bid_BidAdType = 1
	Bid_DSP_AD              Bid_BidAdType = 2
)

var Bid_BidAdType_name = map[int32]string{
	0: "BIDADTYPE_UNDEFINED",
	1: "RETARGET_AD",
	2: "DSP_AD",
}
var Bid_BidAdType_value = map[string]int32{
	"BIDADTYPE_UNDEFINED": 0,
	"RETARGET_AD":         1,
	"DSP_AD":              2,
}

func (x Bid_BidAdType) String() string {
	return proto.EnumName(Bid_BidAdType_name, int32(x))
}
func (Bid_BidAdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

type Pmp struct {
	PrivateAuction uint32      `protobuf:"varint,1,opt,name=private_auction,json=privateAuction" json:"private_auction,omitempty"`
	Deals          []*Pmp_Deal `protobuf:"bytes,2,rep,name=deals" json:"deals,omitempty"`
}

func (m *Pmp) Reset()                    { *m = Pmp{} }
func (m *Pmp) String() string            { return proto.CompactTextString(m) }
func (*Pmp) ProtoMessage()               {}
func (*Pmp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pmp) GetPrivateAuction() uint32 {
	if m != nil {
		return m.PrivateAuction
	}
	return 0
}

func (m *Pmp) GetDeals() []*Pmp_Deal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type Pmp_Deal struct {
	Id       uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BidFloor uint32   `protobuf:"varint,2,opt,name=bid_floor,json=bidFloor" json:"bid_floor,omitempty"`
	Wseat    []string `protobuf:"bytes,3,rep,name=wseat" json:"wseat,omitempty"`
	Wadomain []string `protobuf:"bytes,4,rep,name=wadomain" json:"wadomain,omitempty"`
	At       uint32   `protobuf:"varint,5,opt,name=at" json:"at,omitempty"`
}

func (m *Pmp_Deal) Reset()                    { *m = Pmp_Deal{} }
func (m *Pmp_Deal) String() string            { return proto.CompactTextString(m) }
func (*Pmp_Deal) ProtoMessage()               {}
func (*Pmp_Deal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Pmp_Deal) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pmp_Deal) GetBidFloor() uint32 {
	if m != nil {
		return m.BidFloor
	}
	return 0
}

func (m *Pmp_Deal) GetWseat() []string {
	if m != nil {
		return m.Wseat
	}
	return nil
}

func (m *Pmp_Deal) GetWadomain() []string {
	if m != nil {
		return m.Wadomain
	}
	return nil
}

func (m *Pmp_Deal) GetAt() uint32 {
	if m != nil {
		return m.At
	}
	return 0
}

type AdSlot struct {
	Id               string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Banner           []*AdSlot_Banner `protobuf:"bytes,2,rep,name=banner" json:"banner,omitempty"`
	AdType           []AdType         `protobuf:"varint,3,rep,packed,name=ad_type,json=adType,enum=toutiao_ssp.api.AdType" json:"ad_type,omitempty"`
	BidFloor         uint32           `protobuf:"varint,4,opt,name=bid_floor,json=bidFloor" json:"bid_floor,omitempty"`
	Pmp              *Pmp             `protobuf:"bytes,5,opt,name=pmp" json:"pmp,omitempty"`
	PatchVideoLength uint32           `protobuf:"varint,6,opt,name=patch_video_length,json=patchVideoLength" json:"patch_video_length,omitempty"`
	PatchVideoTitle  string           `protobuf:"bytes,7,opt,name=patch_video_title,json=patchVideoTitle" json:"patch_video_title,omitempty"`
	ChannelId        uint64           `protobuf:"varint,8,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Timestamp        uint64           `protobuf:"varint,9,opt,name=timestamp" json:"timestamp,omitempty"`
	Keywords         []string         `protobuf:"bytes,10,rep,name=keywords" json:"keywords,omitempty"`
}

func (m *AdSlot) Reset()                    { *m = AdSlot{} }
func (m *AdSlot) String() string            { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()               {}
func (*AdSlot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AdSlot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdSlot) GetBanner() []*AdSlot_Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *AdSlot) GetAdType() []AdType {
	if m != nil {
		return m.AdType
	}
	return nil
}

func (m *AdSlot) GetBidFloor() uint32 {
	if m != nil {
		return m.BidFloor
	}
	return 0
}

func (m *AdSlot) GetPmp() *Pmp {
	if m != nil {
		return m.Pmp
	}
	return nil
}

func (m *AdSlot) GetPatchVideoLength() uint32 {
	if m != nil {
		return m.PatchVideoLength
	}
	return 0
}

func (m *AdSlot) GetPatchVideoTitle() string {
	if m != nil {
		return m.PatchVideoTitle
	}
	return ""
}

func (m *AdSlot) GetChannelId() uint64 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *AdSlot) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AdSlot) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type AdSlot_Banner struct {
	Width    uint32          `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height   uint32          `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Pos      AdSlot_Position `protobuf:"varint,3,opt,name=pos,enum=toutiao_ssp.api.AdSlot_Position" json:"pos,omitempty"`
	Sequence string          `protobuf:"bytes,4,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *AdSlot_Banner) Reset()                    { *m = AdSlot_Banner{} }
func (m *AdSlot_Banner) String() string            { return proto.CompactTextString(m) }
func (*AdSlot_Banner) ProtoMessage()               {}
func (*AdSlot_Banner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *AdSlot_Banner) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AdSlot_Banner) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AdSlot_Banner) GetPos() AdSlot_Position {
	if m != nil {
		return m.Pos
	}
	return AdSlot_UNDEFINED
}

func (m *AdSlot_Banner) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

type Publisher struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cat    string `protobuf:"bytes,3,opt,name=cat" json:"cat,omitempty"`
	Domain string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
}

func (m *Publisher) Reset()                    { *m = Publisher{} }
func (m *Publisher) String() string            { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()               {}
func (*Publisher) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Publisher) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Publisher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Publisher) GetCat() string {
	if m != nil {
		return m.Cat
	}
	return ""
}

func (m *Publisher) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type Content struct {
	Id            string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title         string            `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Series        string            `protobuf:"bytes,3,opt,name=series" json:"series,omitempty"`
	Url           string            `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Keywords      string            `protobuf:"bytes,5,opt,name=keywords" json:"keywords,omitempty"`
	Contentrating string            `protobuf:"bytes,6,opt,name=contentrating" json:"contentrating,omitempty"`
	Userrating    string            `protobuf:"bytes,7,opt,name=userrating" json:"userrating,omitempty"`
	Context       string            `protobuf:"bytes,8,opt,name=context" json:"context,omitempty"`
	Producer      *Content_Producer `protobuf:"bytes,9,opt,name=producer" json:"producer,omitempty"`
	Language      string            `protobuf:"bytes,10,opt,name=language" json:"language,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Content) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Content) GetSeries() string {
	if m != nil {
		return m.Series
	}
	return ""
}

func (m *Content) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Content) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *Content) GetContentrating() string {
	if m != nil {
		return m.Contentrating
	}
	return ""
}

func (m *Content) GetUserrating() string {
	if m != nil {
		return m.Userrating
	}
	return ""
}

func (m *Content) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Content) GetProducer() *Content_Producer {
	if m != nil {
		return m.Producer
	}
	return nil
}

func (m *Content) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type Content_Producer struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cat    string `protobuf:"bytes,3,opt,name=cat" json:"cat,omitempty"`
	Domain string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
}

func (m *Content_Producer) Reset()                    { *m = Content_Producer{} }
func (m *Content_Producer) String() string            { return proto.CompactTextString(m) }
func (*Content_Producer) ProtoMessage()               {}
func (*Content_Producer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Content_Producer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Content_Producer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Content_Producer) GetCat() string {
	if m != nil {
		return m.Cat
	}
	return ""
}

func (m *Content_Producer) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type App struct {
	Id            string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain        string     `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Ver           string     `protobuf:"bytes,4,opt,name=ver" json:"ver,omitempty"`
	Bundle        string     `protobuf:"bytes,5,opt,name=bundle" json:"bundle,omitempty"`
	Privacypolicy uint32     `protobuf:"varint,6,opt,name=privacypolicy" json:"privacypolicy,omitempty"`
	Paid          uint32     `protobuf:"varint,7,opt,name=paid" json:"paid,omitempty"`
	Publisher     *Publisher `protobuf:"bytes,8,opt,name=publisher" json:"publisher,omitempty"`
	Content       *Content   `protobuf:"bytes,9,opt,name=content" json:"content,omitempty"`
	Keywords      string     `protobuf:"bytes,10,opt,name=keywords" json:"keywords,omitempty"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *App) GetVer() string {
	if m != nil {
		return m.Ver
	}
	return ""
}

func (m *App) GetBundle() string {
	if m != nil {
		return m.Bundle
	}
	return ""
}

func (m *App) GetPrivacypolicy() uint32 {
	if m != nil {
		return m.Privacypolicy
	}
	return 0
}

func (m *App) GetPaid() uint32 {
	if m != nil {
		return m.Paid
	}
	return 0
}

func (m *App) GetPublisher() *Publisher {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *App) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *App) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

type Geo struct {
	Lat     float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Lon     float64 `protobuf:"fixed64,2,opt,name=lon" json:"lon,omitempty"`
	Country string  `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	Region  string  `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	City    string  `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	Type    string  `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
}

func (m *Geo) Reset()                    { *m = Geo{} }
func (m *Geo) String() string            { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()               {}
func (*Geo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Geo) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Geo) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Geo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Geo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Geo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Geo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Device struct {
	Dnt            bool                  `protobuf:"varint,1,opt,name=dnt" json:"dnt,omitempty"`
	Ua             string                `protobuf:"bytes,2,opt,name=ua" json:"ua,omitempty"`
	Ip             string                `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Geo            *Geo                  `protobuf:"bytes,4,opt,name=geo" json:"geo,omitempty"`
	DeviceId       string                `protobuf:"bytes,5,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceIdMd5    string                `protobuf:"bytes,6,opt,name=device_id_md5,json=deviceIdMd5" json:"device_id_md5,omitempty"`
	Carrier        string                `protobuf:"bytes,7,opt,name=carrier" json:"carrier,omitempty"`
	Language       string                `protobuf:"bytes,8,opt,name=language" json:"language,omitempty"`
	Make           string                `protobuf:"bytes,9,opt,name=make" json:"make,omitempty"`
	Model          string                `protobuf:"bytes,10,opt,name=model" json:"model,omitempty"`
	Os             string                `protobuf:"bytes,11,opt,name=os" json:"os,omitempty"`
	Osv            string                `protobuf:"bytes,12,opt,name=osv" json:"osv,omitempty"`
	Js             bool                  `protobuf:"varint,13,opt,name=js" json:"js,omitempty"`
	ConnectionType Device_ConnectionType `protobuf:"varint,14,opt,name=connection_type,json=connectionType,enum=toutiao_ssp.api.Device_ConnectionType" json:"connection_type,omitempty"`
	DeviceType     Device_DeviceType     `protobuf:"varint,15,opt,name=device_type,json=deviceType,enum=toutiao_ssp.api.Device_DeviceType" json:"device_type,omitempty"`
	AndroidId      string                `protobuf:"bytes,16,opt,name=android_id,json=androidId" json:"android_id,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Device) GetDnt() bool {
	if m != nil {
		return m.Dnt
	}
	return false
}

func (m *Device) GetUa() string {
	if m != nil {
		return m.Ua
	}
	return ""
}

func (m *Device) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Device) GetGeo() *Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Device) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Device) GetDeviceIdMd5() string {
	if m != nil {
		return m.DeviceIdMd5
	}
	return ""
}

func (m *Device) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *Device) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Device) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Device) GetOsv() string {
	if m != nil {
		return m.Osv
	}
	return ""
}

func (m *Device) GetJs() bool {
	if m != nil {
		return m.Js
	}
	return false
}

func (m *Device) GetConnectionType() Device_ConnectionType {
	if m != nil {
		return m.ConnectionType
	}
	return Device_CONNECTIONTYPE_UNDEFINED
}

func (m *Device) GetDeviceType() Device_DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return Device_DEVICETYPE_UNDEFINED
}

func (m *Device) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

type Data struct {
	Id      string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Segment []*Data_Segment `protobuf:"bytes,3,rep,name=segment" json:"segment,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Data) GetSegment() []*Data_Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

type Data_Segment struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Data_Segment) Reset()                    { *m = Data_Segment{} }
func (m *Data_Segment) String() string            { return proto.CompactTextString(m) }
func (*Data_Segment) ProtoMessage()               {}
func (*Data_Segment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *Data_Segment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Data_Segment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Data_Segment) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type User struct {
	Id       string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	BuyerId  string      `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId" json:"buyer_id,omitempty"`
	Yob      string      `protobuf:"bytes,3,opt,name=yob" json:"yob,omitempty"`
	Gender   User_Gender `protobuf:"varint,4,opt,name=gender,enum=toutiao_ssp.api.User_Gender" json:"gender,omitempty"`
	Keywords string      `protobuf:"bytes,5,opt,name=keywords" json:"keywords,omitempty"`
	Geo      *Geo        `protobuf:"bytes,6,opt,name=geo" json:"geo,omitempty"`
	Data     []*Data     `protobuf:"bytes,7,rep,name=data" json:"data,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *User) GetYob() string {
	if m != nil {
		return m.Yob
	}
	return ""
}

func (m *User) GetGender() User_Gender {
	if m != nil {
		return m.Gender
	}
	return User_GENDER_UNDEFINED
}

func (m *User) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *User) GetGeo() *Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *User) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrivateReq struct {
	Materials []*PrivateReq_MaterialInfo `protobuf:"bytes,1,rep,name=materials" json:"materials,omitempty"`
	// 京东地域汉字
	AreaCnName string `protobuf:"bytes,2,opt,name=area_cn_name,json=areaCnName" json:"area_cn_name,omitempty"`
	// 京东地域id
	AreaId string `protobuf:"bytes,3,opt,name=area_id,json=areaId" json:"area_id,omitempty"`
}

func (m *PrivateReq) Reset()                    { *m = PrivateReq{} }
func (m *PrivateReq) String() string            { return proto.CompactTextString(m) }
func (*PrivateReq) ProtoMessage()               {}
func (*PrivateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PrivateReq) GetMaterials() []*PrivateReq_MaterialInfo {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *PrivateReq) GetAreaCnName() string {
	if m != nil {
		return m.AreaCnName
	}
	return ""
}

func (m *PrivateReq) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

type PrivateReq_MaterialInfo struct {
	// 请求素材id
	AdId string `protobuf:"bytes,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	// 请求广告主id
	AdvertiserId string `protobuf:"bytes,2,opt,name=advertiser_id,json=advertiserId" json:"advertiser_id,omitempty"`
}

func (m *PrivateReq_MaterialInfo) Reset()                    { *m = PrivateReq_MaterialInfo{} }
func (m *PrivateReq_MaterialInfo) String() string            { return proto.CompactTextString(m) }
func (*PrivateReq_MaterialInfo) ProtoMessage()               {}
func (*PrivateReq_MaterialInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *PrivateReq_MaterialInfo) GetAdId() string {
	if m != nil {
		return m.AdId
	}
	return ""
}

func (m *PrivateReq_MaterialInfo) GetAdvertiserId() string {
	if m != nil {
		return m.AdvertiserId
	}
	return ""
}

type BidRequest struct {
	RequestId  string                `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiVersion string                `protobuf:"bytes,2,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Adslots    []*AdSlot             `protobuf:"bytes,3,rep,name=adslots" json:"adslots,omitempty"`
	App        *App                  `protobuf:"bytes,4,opt,name=app" json:"app,omitempty"`
	Device     *Device               `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
	User       *User                 `protobuf:"bytes,6,opt,name=user" json:"user,omitempty"`
	BidReqType BidRequest_BidReqType `protobuf:"varint,7,opt,name=bid_req_type,json=bidReqType,enum=toutiao_ssp.api.BidRequest_BidReqType" json:"bid_req_type,omitempty"`
	Preq       *PrivateReq           `protobuf:"bytes,8,opt,name=preq" json:"preq,omitempty"`
}

func (m *BidRequest) Reset()                    { *m = BidRequest{} }
func (m *BidRequest) String() string            { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()               {}
func (*BidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BidRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BidRequest) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *BidRequest) GetAdslots() []*AdSlot {
	if m != nil {
		return m.Adslots
	}
	return nil
}

func (m *BidRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetBidReqType() BidRequest_BidReqType {
	if m != nil {
		return m.BidReqType
	}
	return BidRequest_BIDREQTYPE_UNDEFINED
}

func (m *BidRequest) GetPreq() *PrivateReq {
	if m != nil {
		return m.Preq
	}
	return nil
}

type MaterialMeta struct {
	AdType          AdType                     `protobuf:"varint,1,opt,name=ad_type,json=adType,enum=toutiao_ssp.api.AdType" json:"ad_type,omitempty"`
	Nurl            string                     `protobuf:"bytes,2,opt,name=nurl" json:"nurl,omitempty"`
	Title           string                     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Source          string                     `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	ImageBanner     *MaterialMeta_ImageMeta    `protobuf:"bytes,5,opt,name=image_banner,json=imageBanner" json:"image_banner,omitempty"`
	External        *MaterialMeta_ExternalMeta `protobuf:"bytes,6,opt,name=external" json:"external,omitempty"`
	AndroidApp      *MaterialMeta_AndroidApp   `protobuf:"bytes,7,opt,name=android_app,json=androidApp" json:"android_app,omitempty"`
	IosApp          *MaterialMeta_IosApp       `protobuf:"bytes,8,opt,name=ios_app,json=iosApp" json:"ios_app,omitempty"`
	ShowUrl         []string                   `protobuf:"bytes,9,rep,name=show_url,json=showUrl" json:"show_url,omitempty"`
	ClickUrl        []string                   `protobuf:"bytes,10,rep,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	IsInapp         bool                       `protobuf:"varint,11,opt,name=is_inapp,json=isInapp" json:"is_inapp,omitempty"`
	Ext             string                     `protobuf:"bytes,12,opt,name=ext" json:"ext,omitempty"`
	LpOpenUrl       string                     `protobuf:"bytes,13,opt,name=lp_open_url,json=lpOpenUrl" json:"lp_open_url,omitempty"`
	VideoPlayStart  []string                   `protobuf:"bytes,14,rep,name=video_play_start,json=videoPlayStart" json:"video_play_start,omitempty"`
	VideoPlayFinish []string                   `protobuf:"bytes,15,rep,name=video_play_finish,json=videoPlayFinish" json:"video_play_finish,omitempty"`
	SourceAvatar    string                     `protobuf:"bytes,16,opt,name=source_avatar,json=sourceAvatar" json:"source_avatar,omitempty"`
	SplashCreatives []*MaterialMeta_ImageMeta  `protobuf:"bytes,17,rep,name=splash_creatives,json=splashCreatives" json:"splash_creatives,omitempty"`
}

func (m *MaterialMeta) Reset()                    { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()               {}
func (*MaterialMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MaterialMeta) GetAdType() AdType {
	if m != nil {
		return m.AdType
	}
	return AdType_TOUTIAO_ADTYPE_UNDEFINED
}

func (m *MaterialMeta) GetNurl() string {
	if m != nil {
		return m.Nurl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MaterialMeta) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MaterialMeta) GetImageBanner() *MaterialMeta_ImageMeta {
	if m != nil {
		return m.ImageBanner
	}
	return nil
}

func (m *MaterialMeta) GetExternal() *MaterialMeta_ExternalMeta {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *MaterialMeta) GetAndroidApp() *MaterialMeta_AndroidApp {
	if m != nil {
		return m.AndroidApp
	}
	return nil
}

func (m *MaterialMeta) GetIosApp() *MaterialMeta_IosApp {
	if m != nil {
		return m.IosApp
	}
	return nil
}

func (m *MaterialMeta) GetShowUrl() []string {
	if m != nil {
		return m.ShowUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() []string {
	if m != nil {
		return m.ClickUrl
	}
	return nil
}

func (m *MaterialMeta) GetIsInapp() bool {
	if m != nil {
		return m.IsInapp
	}
	return false
}

func (m *MaterialMeta) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *MaterialMeta) GetLpOpenUrl() string {
	if m != nil {
		return m.LpOpenUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoPlayStart() []string {
	if m != nil {
		return m.VideoPlayStart
	}
	return nil
}

func (m *MaterialMeta) GetVideoPlayFinish() []string {
	if m != nil {
		return m.VideoPlayFinish
	}
	return nil
}

func (m *MaterialMeta) GetSourceAvatar() string {
	if m != nil {
		return m.SourceAvatar
	}
	return ""
}

func (m *MaterialMeta) GetSplashCreatives() []*MaterialMeta_ImageMeta {
	if m != nil {
		return m.SplashCreatives
	}
	return nil
}

type MaterialMeta_ImageMeta struct {
	Description    string   `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Width          uint32   `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height         uint32   `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Url            string   `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Urls           []string `protobuf:"bytes,5,rep,name=urls" json:"urls,omitempty"`
	DateTimestamp  uint64   `protobuf:"varint,6,opt,name=date_timestamp,json=dateTimestamp" json:"date_timestamp,omitempty"`
	StartTimestamp uint64   `protobuf:"varint,7,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64   `protobuf:"varint,8,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
}

func (m *MaterialMeta_ImageMeta) Reset()                    { *m = MaterialMeta_ImageMeta{} }
func (m *MaterialMeta_ImageMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_ImageMeta) ProtoMessage()               {}
func (*MaterialMeta_ImageMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *MaterialMeta_ImageMeta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MaterialMeta_ImageMeta) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MaterialMeta_ImageMeta) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *MaterialMeta_ImageMeta) GetDateTimestamp() uint64 {
	if m != nil {
		return m.DateTimestamp
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetStartTimestamp() uint64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetEndTimestamp() uint64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type MaterialMeta_ExternalMeta struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *MaterialMeta_ExternalMeta) Reset()                    { *m = MaterialMeta_ExternalMeta{} }
func (m *MaterialMeta_ExternalMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_ExternalMeta) ProtoMessage()               {}
func (*MaterialMeta_ExternalMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 1} }

func (m *MaterialMeta_ExternalMeta) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type MaterialMeta_AndroidApp struct {
	AppName     string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	OpenUrl     string `protobuf:"bytes,3,opt,name=open_url,json=openUrl" json:"open_url,omitempty"`
	Package     string `protobuf:"bytes,4,opt,name=package" json:"package,omitempty"`
	WebUrl      string `protobuf:"bytes,5,opt,name=web_url,json=webUrl" json:"web_url,omitempty"`
}

func (m *MaterialMeta_AndroidApp) Reset()                    { *m = MaterialMeta_AndroidApp{} }
func (m *MaterialMeta_AndroidApp) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_AndroidApp) ProtoMessage()               {}
func (*MaterialMeta_AndroidApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 2} }

func (m *MaterialMeta_AndroidApp) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetOpenUrl() string {
	if m != nil {
		return m.OpenUrl
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetWebUrl() string {
	if m != nil {
		return m.WebUrl
	}
	return ""
}

type MaterialMeta_IosApp struct {
	AppName     string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	OpenUrl     string `protobuf:"bytes,3,opt,name=open_url,json=openUrl" json:"open_url,omitempty"`
	Appleid     string `protobuf:"bytes,4,opt,name=appleid" json:"appleid,omitempty"`
	IpaUrl      string `protobuf:"bytes,5,opt,name=ipa_url,json=ipaUrl" json:"ipa_url,omitempty"`
}

func (m *MaterialMeta_IosApp) Reset()                    { *m = MaterialMeta_IosApp{} }
func (m *MaterialMeta_IosApp) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_IosApp) ProtoMessage()               {}
func (*MaterialMeta_IosApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 3} }

func (m *MaterialMeta_IosApp) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetOpenUrl() string {
	if m != nil {
		return m.OpenUrl
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetAppleid() string {
	if m != nil {
		return m.Appleid
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetIpaUrl() string {
	if m != nil {
		return m.IpaUrl
	}
	return ""
}

type Bid struct {
	Id        string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AdslotId  string        `protobuf:"bytes,2,opt,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	Price     uint32        `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Adid      uint64        `protobuf:"varint,4,opt,name=adid" json:"adid,omitempty"`
	Creative  *MaterialMeta `protobuf:"bytes,5,opt,name=creative" json:"creative,omitempty"`
	Dealid    string        `protobuf:"bytes,6,opt,name=dealid" json:"dealid,omitempty"`
	Cid       string        `protobuf:"bytes,7,opt,name=cid" json:"cid,omitempty"`
	BidAdType Bid_BidAdType `protobuf:"varint,8,opt,name=bid_ad_type,json=bidAdType,enum=toutiao_ssp.api.Bid_BidAdType" json:"bid_ad_type,omitempty"`
	Quality   float64       `protobuf:"fixed64,9,opt,name=quality" json:"quality,omitempty"`
	Ctr       float64       `protobuf:"fixed64,10,opt,name=ctr" json:"ctr,omitempty"`
}

func (m *Bid) Reset()                    { *m = Bid{} }
func (m *Bid) String() string            { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()               {}
func (*Bid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Bid) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bid) GetAdslotId() string {
	if m != nil {
		return m.AdslotId
	}
	return ""
}

func (m *Bid) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Bid) GetAdid() uint64 {
	if m != nil {
		return m.Adid
	}
	return 0
}

func (m *Bid) GetCreative() *MaterialMeta {
	if m != nil {
		return m.Creative
	}
	return nil
}

func (m *Bid) GetDealid() string {
	if m != nil {
		return m.Dealid
	}
	return ""
}

func (m *Bid) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Bid) GetBidAdType() Bid_BidAdType {
	if m != nil {
		return m.BidAdType
	}
	return Bid_BIDADTYPE_UNDEFINED
}

func (m *Bid) GetQuality() float64 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *Bid) GetCtr() float64 {
	if m != nil {
		return m.Ctr
	}
	return 0
}

type SeatBid struct {
	Ads  []*Bid `protobuf:"bytes,1,rep,name=ads" json:"ads,omitempty"`
	Seat string `protobuf:"bytes,2,opt,name=seat" json:"seat,omitempty"`
}

func (m *SeatBid) Reset()                    { *m = SeatBid{} }
func (m *SeatBid) String() string            { return proto.CompactTextString(m) }
func (*SeatBid) ProtoMessage()               {}
func (*SeatBid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SeatBid) GetAds() []*Bid {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *SeatBid) GetSeat() string {
	if m != nil {
		return m.Seat
	}
	return ""
}

type BidResponse struct {
	RequestId string     `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Seatbids  []*SeatBid `protobuf:"bytes,2,rep,name=seatbids" json:"seatbids,omitempty"`
	ErrorCode uint64     `protobuf:"varint,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *BidResponse) Reset()                    { *m = BidResponse{} }
func (m *BidResponse) String() string            { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()               {}
func (*BidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BidResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BidResponse) GetSeatbids() []*SeatBid {
	if m != nil {
		return m.Seatbids
	}
	return nil
}

func (m *BidResponse) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type DspClickNotification struct {
	Dspid     uint64 `protobuf:"varint,1,opt,name=dspid" json:"dspid,omitempty"`
	ClickUuid string `protobuf:"bytes,2,opt,name=click_uuid,json=clickUuid" json:"click_uuid,omitempty"`
	Price     uint32 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
}

func (m *DspClickNotification) Reset()                    { *m = DspClickNotification{} }
func (m *DspClickNotification) String() string            { return proto.CompactTextString(m) }
func (*DspClickNotification) ProtoMessage()               {}
func (*DspClickNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DspClickNotification) GetDspid() uint64 {
	if m != nil {
		return m.Dspid
	}
	return 0
}

func (m *DspClickNotification) GetClickUuid() string {
	if m != nil {
		return m.ClickUuid
	}
	return ""
}

func (m *DspClickNotification) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*Pmp)(nil), "toutiao_ssp.api.Pmp")
	proto.RegisterType((*Pmp_Deal)(nil), "toutiao_ssp.api.Pmp.Deal")
	proto.RegisterType((*AdSlot)(nil), "toutiao_ssp.api.AdSlot")
	proto.RegisterType((*AdSlot_Banner)(nil), "toutiao_ssp.api.AdSlot.Banner")
	proto.RegisterType((*Publisher)(nil), "toutiao_ssp.api.Publisher")
	proto.RegisterType((*Content)(nil), "toutiao_ssp.api.Content")
	proto.RegisterType((*Content_Producer)(nil), "toutiao_ssp.api.Content.Producer")
	proto.RegisterType((*App)(nil), "toutiao_ssp.api.App")
	proto.RegisterType((*Geo)(nil), "toutiao_ssp.api.Geo")
	proto.RegisterType((*Device)(nil), "toutiao_ssp.api.Device")
	proto.RegisterType((*Data)(nil), "toutiao_ssp.api.Data")
	proto.RegisterType((*Data_Segment)(nil), "toutiao_ssp.api.Data.Segment")
	proto.RegisterType((*User)(nil), "toutiao_ssp.api.User")
	proto.RegisterType((*PrivateReq)(nil), "toutiao_ssp.api.PrivateReq")
	proto.RegisterType((*PrivateReq_MaterialInfo)(nil), "toutiao_ssp.api.PrivateReq.MaterialInfo")
	proto.RegisterType((*BidRequest)(nil), "toutiao_ssp.api.BidRequest")
	proto.RegisterType((*MaterialMeta)(nil), "toutiao_ssp.api.MaterialMeta")
	proto.RegisterType((*MaterialMeta_ImageMeta)(nil), "toutiao_ssp.api.MaterialMeta.ImageMeta")
	proto.RegisterType((*MaterialMeta_ExternalMeta)(nil), "toutiao_ssp.api.MaterialMeta.ExternalMeta")
	proto.RegisterType((*MaterialMeta_AndroidApp)(nil), "toutiao_ssp.api.MaterialMeta.AndroidApp")
	proto.RegisterType((*MaterialMeta_IosApp)(nil), "toutiao_ssp.api.MaterialMeta.IosApp")
	proto.RegisterType((*Bid)(nil), "toutiao_ssp.api.Bid")
	proto.RegisterType((*SeatBid)(nil), "toutiao_ssp.api.SeatBid")
	proto.RegisterType((*BidResponse)(nil), "toutiao_ssp.api.BidResponse")
	proto.RegisterType((*DspClickNotification)(nil), "toutiao_ssp.api.DspClickNotification")
	proto.RegisterEnum("toutiao_ssp.api.AdType", AdType_name, AdType_value)
	proto.RegisterEnum("toutiao_ssp.api.AdSlot_Position", AdSlot_Position_name, AdSlot_Position_value)
	proto.RegisterEnum("toutiao_ssp.api.Device_ConnectionType", Device_ConnectionType_name, Device_ConnectionType_value)
	proto.RegisterEnum("toutiao_ssp.api.Device_DeviceType", Device_DeviceType_name, Device_DeviceType_value)
	proto.RegisterEnum("toutiao_ssp.api.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterEnum("toutiao_ssp.api.BidRequest_BidReqType", BidRequest_BidReqType_name, BidRequest_BidReqType_value)
	proto.RegisterEnum("toutiao_ssp.api.Bid_BidAdType", Bid_BidAdType_name, Bid_BidAdType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x39, 0xcd, 0x6e, 0x23, 0xc7,
	0xd1, 0x1f, 0x7f, 0x44, 0x72, 0x8a, 0x22, 0x35, 0xdb, 0x2b, 0x7b, 0x67, 0xe9, 0xdd, 0xfd, 0x64,
	0xda, 0xb1, 0x15, 0x23, 0x90, 0x13, 0xc5, 0xce, 0xcf, 0xc1, 0x01, 0x28, 0x72, 0x24, 0x8d, 0x2d,
	0x91, 0xcc, 0x88, 0x5a, 0xdb, 0x01, 0x82, 0x41, 0x93, 0xdd, 0x2b, 0xb5, 0x77, 0x38, 0x33, 0x3b,
	0x33, 0x94, 0xcc, 0x63, 0x10, 0x20, 0x87, 0x00, 0xb9, 0x25, 0x40, 0x1e, 0x21, 0x40, 0x0e, 0x79,
	0x86, 0x3c, 0x41, 0x6e, 0x01, 0x72, 0xc8, 0x3b, 0xe4, 0x94, 0x73, 0x50, 0xdd, 0x3d, 0x43, 0x72,
	0x49, 0xed, 0xee, 0x21, 0x39, 0x08, 0xac, 0xaa, 0xae, 0xae, 0xae, 0xae, 0xaa, 0xae, 0x9f, 0x11,
	0x34, 0xa6, 0x3c, 0x49, 0xe8, 0x15, 0x3f, 0x88, 0xe2, 0x30, 0x0d, 0xc9, 0x4e, 0x1a, 0xce, 0x52,
	0x41, 0x43, 0x2f, 0x49, 0xa2, 0x03, 0x1a, 0x89, 0xf6, 0xdf, 0x0b, 0x50, 0x1a, 0x4e, 0x23, 0xf2,
	0x21, 0xec, 0x44, 0xb1, 0xb8, 0xa1, 0x29, 0xf7, 0xe8, 0x6c, 0x92, 0x8a, 0x30, 0xb0, 0x0a, 0x7b,
	0x85, 0xfd, 0x86, 0xdb, 0xd4, 0xe4, 0x8e, 0xa2, 0x92, 0x8f, 0x61, 0x8b, 0x71, 0xea, 0x27, 0x56,
	0x71, 0xaf, 0xb4, 0x5f, 0x3f, 0x7c, 0x78, 0xf0, 0x92, 0xc4, 0x83, 0xe1, 0x34, 0x3a, 0xe8, 0x71,
	0xea, 0xbb, 0x8a, 0xaf, 0x35, 0x83, 0x32, 0xa2, 0xa4, 0x09, 0x45, 0xc1, 0xb4, 0xd0, 0xa2, 0x60,
	0xe4, 0x1d, 0x30, 0xc6, 0x82, 0x79, 0xcf, 0xfc, 0x30, 0x8c, 0xad, 0xa2, 0x24, 0xd7, 0xc6, 0x82,
	0x1d, 0x23, 0x4e, 0x76, 0x61, 0xeb, 0x36, 0xe1, 0x34, 0xb5, 0x4a, 0x7b, 0xa5, 0x7d, 0xc3, 0x55,
	0x08, 0x69, 0x41, 0xed, 0x96, 0xb2, 0x70, 0x4a, 0x45, 0x60, 0x95, 0xe5, 0x42, 0x8e, 0xa3, 0x78,
	0x9a, 0x5a, 0x5b, 0x4a, 0x3c, 0x4d, 0xdb, 0x7f, 0x2b, 0x43, 0xa5, 0xc3, 0x2e, 0xfc, 0x30, 0x5d,
	0x3a, 0xd9, 0x90, 0x27, 0xff, 0x08, 0x2a, 0x63, 0x1a, 0x04, 0x3c, 0xd6, 0x77, 0x78, 0xb2, 0x76,
	0x07, 0xb5, 0xf1, 0xe0, 0x48, 0x72, 0xb9, 0x9a, 0x9b, 0x7c, 0x1f, 0xaa, 0x94, 0x79, 0xe9, 0x3c,
	0xe2, 0x52, 0xad, 0xe6, 0xe1, 0x83, 0x0d, 0x1b, 0x47, 0xf3, 0x88, 0xbb, 0x15, 0x2a, 0x7f, 0x57,
	0xef, 0x58, 0x7e, 0xe9, 0x8e, 0x1f, 0x40, 0x29, 0x9a, 0x46, 0x52, 0xe5, 0xfa, 0xe1, 0xee, 0x26,
	0x3b, 0xba, 0xc8, 0x40, 0xbe, 0x07, 0x24, 0xa2, 0xe9, 0xe4, 0xda, 0xbb, 0x11, 0x8c, 0x87, 0x9e,
	0xcf, 0x83, 0xab, 0xf4, 0xda, 0xaa, 0x48, 0x69, 0xa6, 0x5c, 0x79, 0x8a, 0x0b, 0x67, 0x92, 0x4e,
	0x3e, 0x82, 0x7b, 0xcb, 0xdc, 0xa9, 0x48, 0x7d, 0x6e, 0x55, 0xe5, 0xdd, 0x77, 0x16, 0xcc, 0x23,
	0x24, 0x93, 0xc7, 0x00, 0x93, 0x6b, 0xbc, 0x9b, 0xef, 0x09, 0x66, 0xd5, 0xf6, 0x0a, 0xfb, 0x65,
	0xd7, 0xd0, 0x14, 0x87, 0x91, 0x47, 0x60, 0xa4, 0x62, 0xca, 0x93, 0x94, 0x4e, 0x23, 0xcb, 0x50,
	0xab, 0x39, 0x01, 0x9d, 0xf1, 0x9c, 0xcf, 0x6f, 0xc3, 0x98, 0x25, 0x16, 0x28, 0x67, 0x64, 0x78,
	0xeb, 0x37, 0x05, 0xa8, 0x28, 0xe3, 0x49, 0x4f, 0x0a, 0x96, 0x5e, 0x6b, 0xcf, 0x2b, 0x84, 0xbc,
	0x0d, 0x95, 0x6b, 0x2e, 0xae, 0xae, 0x53, 0xed, 0x79, 0x8d, 0x91, 0x43, 0x28, 0x45, 0x61, 0x62,
	0x95, 0xf6, 0x0a, 0xfb, 0xcd, 0xc3, 0xbd, 0xbb, 0xfc, 0x32, 0x0c, 0x13, 0x81, 0xc1, 0xe8, 0x22,
	0x33, 0x2a, 0x92, 0xf0, 0x17, 0x33, 0x1e, 0x4c, 0xb8, 0xb4, 0xb1, 0xe1, 0xe6, 0x78, 0xfb, 0x73,
	0xa8, 0x65, 0xcc, 0xa4, 0x01, 0xc6, 0x65, 0xbf, 0x67, 0x1f, 0x3b, 0x7d, 0xbb, 0x67, 0xfe, 0x1f,
	0x01, 0xa8, 0x5c, 0x0c, 0xcf, 0x3a, 0x17, 0xa7, 0x66, 0x81, 0xd4, 0xa0, 0x7c, 0x6c, 0xdb, 0x3d,
	0xb3, 0x88, 0xd4, 0x9e, 0x3d, 0xea, 0x38, 0x67, 0x66, 0x19, 0x37, 0xb8, 0x76, 0x77, 0x70, 0x7e,
	0x6e, 0xf7, 0x7b, 0x66, 0xad, 0xfd, 0x35, 0x18, 0xc3, 0xd9, 0xd8, 0x17, 0xc9, 0x35, 0x8f, 0xd7,
	0x62, 0x8a, 0x40, 0x39, 0xa0, 0x53, 0x2e, 0xaf, 0x63, 0xb8, 0x12, 0x26, 0x26, 0x94, 0x26, 0x32,
	0x84, 0x91, 0x84, 0x20, 0x5e, 0x3b, 0x0f, 0x5f, 0x24, 0x6a, 0xac, 0xfd, 0xdb, 0x12, 0x54, 0xbb,
	0x61, 0x90, 0xf2, 0x60, 0x3d, 0x5a, 0x77, 0x61, 0x4b, 0x39, 0x51, 0x89, 0x56, 0x08, 0x4a, 0x4a,
	0x78, 0x2c, 0x78, 0xa2, 0xc5, 0x6b, 0x0c, 0xcf, 0x9c, 0xc5, 0xbe, 0x16, 0x8f, 0xe0, 0x8a, 0x9f,
	0xb6, 0x94, 0x79, 0x32, 0x9c, 0xbc, 0x0f, 0x8d, 0x89, 0x3a, 0x36, 0xa6, 0xa9, 0x08, 0xae, 0x64,
	0x54, 0x19, 0xee, 0x2a, 0x91, 0x3c, 0x01, 0x98, 0x25, 0x3c, 0xd6, 0x2c, 0x2a, 0x96, 0x96, 0x28,
	0xc4, 0x82, 0xaa, 0xdc, 0xf0, 0x6d, 0x2a, 0x63, 0xc8, 0x70, 0x33, 0x94, 0x7c, 0x06, 0xb5, 0x28,
	0x0e, 0xd9, 0x6c, 0xc2, 0x63, 0x19, 0x40, 0xf5, 0xc3, 0x77, 0xd7, 0x7c, 0xaa, 0xef, 0x7d, 0x30,
	0xd4, 0x8c, 0x6e, 0xbe, 0x05, 0x55, 0xf7, 0x69, 0x70, 0x35, 0xa3, 0x57, 0xdc, 0x02, 0xa5, 0x7a,
	0x86, 0xb7, 0xbe, 0x82, 0x5a, 0xb6, 0xe3, 0xbf, 0xec, 0x8c, 0xbf, 0x14, 0xa1, 0xd4, 0x89, 0xa2,
	0x37, 0x92, 0xba, 0x90, 0x51, 0x5a, 0x96, 0x81, 0xa7, 0xdd, 0xf0, 0x38, 0x73, 0xc3, 0x0d, 0x8f,
	0x91, 0x73, 0x3c, 0x0b, 0x98, 0xcf, 0xb5, 0x13, 0x34, 0x86, 0x2e, 0x90, 0x19, 0x76, 0x32, 0x8f,
	0x42, 0x5f, 0x4c, 0xe6, 0xfa, 0x61, 0xaf, 0x12, 0xf1, 0xec, 0x88, 0x0a, 0x26, 0x8d, 0xdf, 0x70,
	0x25, 0x4c, 0x7e, 0x02, 0x46, 0x94, 0xc5, 0xa3, 0x34, 0x7c, 0xfd, 0xb0, 0xb5, 0x9e, 0x45, 0x32,
	0x0e, 0x77, 0xc1, 0x4c, 0x0e, 0xb5, 0xc3, 0x82, 0x54, 0x7b, 0xc5, 0xba, 0xcb, 0x2b, 0x6e, 0xc6,
	0xf8, 0xd2, 0x73, 0x5f, 0x09, 0xa3, 0xf6, 0xaf, 0x0b, 0x50, 0x3a, 0xe1, 0x21, 0xde, 0xda, 0xa7,
	0xa9, 0x34, 0x59, 0xc1, 0x45, 0x50, 0x52, 0xc2, 0x40, 0x9a, 0x0c, 0x29, 0x61, 0xa0, 0x82, 0x65,
	0x16, 0xa4, 0xf1, 0x5c, 0x9b, 0x2c, 0x43, 0xd1, 0x42, 0x31, 0xbf, 0xc2, 0xca, 0xa3, 0xfd, 0xa1,
	0x30, 0xbc, 0xfb, 0x44, 0xa4, 0x73, 0x6d, 0x37, 0x09, 0x23, 0x4d, 0xe6, 0x61, 0x15, 0xaf, 0x12,
	0x6e, 0xff, 0x61, 0x0b, 0x2a, 0x3d, 0x7e, 0x23, 0x26, 0xd2, 0xd9, 0x2c, 0x50, 0x8a, 0xd4, 0x5c,
	0x04, 0xd1, 0x99, 0x33, 0xaa, 0x5d, 0x57, 0x9c, 0x51, 0xe9, 0xdc, 0x48, 0x6b, 0x50, 0x14, 0x11,
	0x26, 0xe3, 0x2b, 0x1e, 0xca, 0x93, 0x37, 0x25, 0xe3, 0x13, 0x1e, 0xba, 0xc8, 0x80, 0x19, 0x9d,
	0xc9, 0x33, 0x30, 0x63, 0xea, 0xe7, 0xa4, 0x08, 0x0e, 0x23, 0x6d, 0x68, 0xe4, 0x8b, 0xde, 0x94,
	0x7d, 0xaa, 0xd5, 0xab, 0x67, 0x0c, 0xe7, 0xec, 0x53, 0x79, 0x7f, 0x1a, 0xc7, 0x82, 0xc7, 0xfa,
	0x25, 0x65, 0xe8, 0x4a, 0xb4, 0xd7, 0x56, 0xa3, 0x1d, 0xef, 0x3b, 0xa5, 0xcf, 0xb9, 0x74, 0x97,
	0xe1, 0x4a, 0x18, 0x13, 0xc3, 0x34, 0x64, 0xdc, 0xd7, 0xee, 0x50, 0x08, 0x5e, 0x2c, 0x4c, 0xac,
	0xba, 0xba, 0x58, 0x28, 0x13, 0x42, 0x98, 0xdc, 0x58, 0xdb, 0x2a, 0x12, 0xc3, 0xe4, 0x06, 0x39,
	0xbe, 0x49, 0xac, 0x86, 0xb4, 0x4d, 0xf1, 0x9b, 0x84, 0x0c, 0x60, 0x67, 0x12, 0x06, 0x01, 0x97,
	0xf5, 0x5d, 0x95, 0xb7, 0xa6, 0xcc, 0xbf, 0x1f, 0xac, 0x99, 0x41, 0x99, 0x17, 0x83, 0x43, 0xb3,
	0xcb, 0x6a, 0xd7, 0x9c, 0xac, 0xe0, 0xa4, 0x0b, 0xfa, 0xc6, 0x4a, 0xd8, 0x8e, 0x14, 0xd6, 0xbe,
	0x4b, 0x98, 0xfa, 0x91, 0x82, 0x80, 0xe5, 0x30, 0xd6, 0x26, 0x1a, 0xb0, 0x38, 0x14, 0x0c, 0x2d,
	0x6d, 0x4a, 0xf5, 0x0d, 0x4d, 0x71, 0x58, 0xfb, 0x1b, 0x68, 0xae, 0x6a, 0x41, 0x1e, 0x81, 0xd5,
	0x1d, 0xf4, 0xfb, 0x76, 0x77, 0xe4, 0x0c, 0xfa, 0xa3, 0xaf, 0x87, 0xb6, 0xb7, 0x9c, 0xed, 0x1b,
	0x60, 0x9c, 0x86, 0x01, 0x9f, 0x4f, 0xc2, 0xe9, 0x58, 0x25, 0xfc, 0x2f, 0x9d, 0x63, 0xc7, 0x2c,
	0x92, 0x3a, 0x54, 0x2f, 0xfb, 0x5f, 0xf4, 0x07, 0x5f, 0xf6, 0xcd, 0x12, 0x31, 0x60, 0xab, 0x3f,
	0xf2, 0x0e, 0x4f, 0xcc, 0xb2, 0x06, 0x3f, 0x39, 0x31, 0xb7, 0xda, 0x9f, 0x01, 0x2c, 0x94, 0x24,
	0x16, 0xec, 0xf6, 0xec, 0xa7, 0x4e, 0xd7, 0x5e, 0x3b, 0xc3, 0x80, 0xad, 0xe1, 0xe9, 0xa0, 0x6f,
	0x9b, 0x05, 0x2c, 0x23, 0xa3, 0xce, 0xd1, 0x99, 0x3d, 0x32, 0x8b, 0xed, 0x3f, 0x15, 0xa0, 0xdc,
	0xa3, 0x29, 0x7d, 0xa3, 0x84, 0xf2, 0x63, 0xa8, 0x26, 0xfc, 0x6a, 0x8a, 0x4f, 0xb3, 0x24, 0x9b,
	0x93, 0xc7, 0xeb, 0x76, 0xa3, 0x29, 0x3d, 0xb8, 0x50, 0x4c, 0x6e, 0xc6, 0xdd, 0xea, 0x42, 0x55,
	0xd3, 0xde, 0xe8, 0x9c, 0x5d, 0xd8, 0xba, 0xa1, 0xfe, 0x8c, 0xeb, 0x27, 0xa0, 0x90, 0xf6, 0x9f,
	0x8b, 0x50, 0xbe, 0x4c, 0x36, 0x64, 0xd4, 0x87, 0x50, 0x1b, 0xcf, 0xe6, 0x3c, 0x46, 0x5f, 0x28,
	0x31, 0x55, 0x89, 0x3b, 0x0c, 0x03, 0x6c, 0x1e, 0x8e, 0xb3, 0xc4, 0x3a, 0x0f, 0xc7, 0xe4, 0x13,
	0xa8, 0x5c, 0xf1, 0x80, 0xe9, 0xfc, 0xd7, 0x3c, 0x7c, 0xb4, 0x76, 0x05, 0x3c, 0xe3, 0xe0, 0x44,
	0xf2, 0xb8, 0x9a, 0xf7, 0x95, 0x75, 0x4a, 0xbf, 0xce, 0xca, 0xeb, 0x5e, 0xe7, 0x77, 0xa1, 0xcc,
	0x68, 0x4a, 0xad, 0xaa, 0x34, 0xdd, 0x5b, 0x1b, 0x4d, 0xe7, 0x4a, 0x96, 0x76, 0x07, 0x2a, 0x4a,
	0x01, 0xb2, 0x0b, 0xe6, 0x89, 0xdd, 0xef, 0xd9, 0xee, 0x8a, 0x33, 0x6b, 0x50, 0x3e, 0xef, 0x9c,
	0x69, 0x5f, 0x1e, 0xdb, 0x12, 0x5e, 0x8d, 0x96, 0xf6, 0x3f, 0x0a, 0x00, 0x43, 0xd5, 0x1d, 0xbb,
	0xfc, 0x05, 0x39, 0x06, 0x63, 0x4a, 0x53, 0x1e, 0x0b, 0xec, 0x8e, 0x0b, 0x52, 0x83, 0xfd, 0xf5,
	0x7c, 0x9c, 0xf3, 0x1f, 0x9c, 0x6b, 0x66, 0x27, 0x78, 0x16, 0xba, 0x8b, 0xad, 0x64, 0x0f, 0xb6,
	0x69, 0xcc, 0xa9, 0x37, 0x09, 0xbc, 0x25, 0xb7, 0x01, 0xd2, 0xba, 0x41, 0x1f, 0x9d, 0xf7, 0x00,
	0xaa, 0x92, 0x43, 0xb0, 0xac, 0xec, 0x20, 0xea, 0xb0, 0xd6, 0x29, 0x6c, 0x2f, 0x4b, 0x25, 0xf7,
	0x61, 0x8b, 0xca, 0xf7, 0xa3, 0x3c, 0x59, 0xa6, 0xcc, 0x61, 0xe4, 0x3d, 0x68, 0x50, 0x76, 0xc3,
	0xe3, 0x54, 0x24, 0xcb, 0x0e, 0xdd, 0x5e, 0x10, 0x1d, 0xd6, 0xfe, 0x67, 0x09, 0xe0, 0x48, 0x30,
	0x17, 0x1b, 0xa9, 0x24, 0xc5, 0xd7, 0x18, 0x2b, 0x70, 0x21, 0xcd, 0xd0, 0x14, 0x87, 0x91, 0xff,
	0x87, 0x3a, 0x8d, 0x84, 0x77, 0xc3, 0xe3, 0x44, 0xe8, 0x74, 0x8f, 0x1a, 0x47, 0xe2, 0xa9, 0xa2,
	0x90, 0x1f, 0x60, 0xeb, 0x9c, 0xf8, 0x61, 0x9a, 0xe8, 0xb0, 0x7e, 0x70, 0x47, 0x6f, 0xe7, 0x66,
	0x7c, 0xe8, 0x73, 0x1a, 0x45, 0x77, 0x66, 0xe4, 0x4e, 0x14, 0xb9, 0xc8, 0x40, 0x3e, 0x86, 0x8a,
	0x4a, 0x1b, 0xba, 0x93, 0x7e, 0x70, 0x47, 0xa2, 0x71, 0x35, 0x1b, 0x06, 0x09, 0x36, 0x2f, 0x3a,
	0x9a, 0xde, 0xda, 0x18, 0x9c, 0xae, 0x64, 0x21, 0xa7, 0xb0, 0x8d, 0xfd, 0x7b, 0xcc, 0x5f, 0xa8,
	0x54, 0x56, 0xbd, 0x23, 0x2f, 0x2e, 0x2c, 0xa5, 0x41, 0x95, 0xce, 0xc6, 0x39, 0x4c, 0x3e, 0x86,
	0x72, 0x14, 0xf3, 0x17, 0xba, 0x4e, 0xbf, 0xf3, 0x8a, 0xb8, 0x70, 0x25, 0x63, 0xfb, 0x97, 0x99,
	0xfd, 0xb3, 0xa4, 0x73, 0xe4, 0xf4, 0x5c, 0xfb, 0xe7, 0x6b, 0x49, 0xe7, 0x1e, 0x34, 0x06, 0xfd,
	0xb3, 0xaf, 0x3d, 0xd7, 0x1e, 0x75, 0xdc, 0x13, 0x7b, 0x64, 0x16, 0xc8, 0x36, 0xd4, 0x24, 0xa9,
	0x77, 0x31, 0x34, 0x8b, 0x18, 0xde, 0xd9, 0x9a, 0xd7, 0xe9, 0xf7, 0x24, 0xb5, 0xd4, 0xfe, 0x2b,
	0x2c, 0x42, 0xe5, 0x9c, 0xa7, 0x74, 0x79, 0xb8, 0x29, 0xc8, 0x5b, 0xbe, 0x76, 0xb8, 0xc1, 0xb4,
	0x82, 0xbd, 0x66, 0x96, 0x56, 0xb0, 0xd9, 0xcc, 0x9b, 0xd5, 0xd2, 0xcb, 0xcd, 0x6a, 0x38, 0x8b,
	0xf3, 0xfe, 0x5c, 0x63, 0xe4, 0x73, 0xd8, 0x16, 0x53, 0x7a, 0xc5, 0x3d, 0x3d, 0x8e, 0x29, 0x07,
	0x7e, 0xb8, 0x76, 0xf0, 0xb2, 0xa2, 0x07, 0x0e, 0xee, 0x40, 0xc8, 0xad, 0xcb, 0xcd, 0x7a, 0xce,
	0x38, 0x86, 0x1a, 0xff, 0x36, 0xe5, 0x71, 0x40, 0x7d, 0xed, 0xd9, 0x8f, 0x5e, 0x2d, 0xc7, 0xd6,
	0xdc, 0x52, 0x54, 0xbe, 0x97, 0x38, 0x50, 0xcf, 0xea, 0x0e, 0x86, 0x5f, 0x55, 0x8a, 0xda, 0x7f,
	0xb5, 0xa8, 0x8e, 0xda, 0x80, 0x21, 0x99, 0x15, 0x2d, 0x6c, 0x20, 0x3f, 0x83, 0xaa, 0x08, 0x13,
	0x29, 0x46, 0xb9, 0xfd, 0xfd, 0xd7, 0xdc, 0x2c, 0x4c, 0x50, 0x44, 0x45, 0xc8, 0x5f, 0xcc, 0xb9,
	0xc9, 0x75, 0x78, 0xeb, 0xa1, 0x8d, 0x0d, 0x39, 0x60, 0x55, 0x11, 0xbf, 0x8c, 0x7d, 0xec, 0x42,
	0x26, 0xbe, 0x98, 0x3c, 0x97, 0x6b, 0x7a, 0xf8, 0x92, 0x04, 0x5c, 0x7c, 0x08, 0x35, 0x91, 0x78,
	0x22, 0xc0, 0x73, 0xeb, 0xb2, 0xca, 0x57, 0x45, 0xe2, 0x20, 0x8a, 0xb9, 0x1a, 0xbb, 0x74, 0xdd,
	0x0c, 0x60, 0x87, 0xfe, 0x04, 0xea, 0x7e, 0xe4, 0x85, 0x11, 0x0f, 0xa4, 0xac, 0x86, 0x7a, 0xd9,
	0x7e, 0x34, 0x88, 0x78, 0x80, 0xc2, 0xf6, 0xc1, 0x54, 0x83, 0x64, 0xe4, 0xd3, 0xb9, 0x97, 0xa4,
	0x34, 0x4e, 0xad, 0xa6, 0x3c, 0xb0, 0x29, 0xe9, 0x43, 0x9f, 0xce, 0x2f, 0x90, 0x8a, 0x83, 0xe7,
	0x12, 0xe7, 0x33, 0x11, 0x88, 0xe4, 0xda, 0xda, 0x91, 0xac, 0x3b, 0x39, 0xeb, 0xb1, 0x24, 0x63,
	0x0a, 0x52, 0x21, 0xe0, 0xd1, 0x1b, 0x9a, 0xd2, 0x58, 0xd7, 0xf7, 0x6d, 0x45, 0xec, 0x48, 0x1a,
	0x71, 0xc1, 0x4c, 0x22, 0x9f, 0x26, 0xd7, 0xde, 0x24, 0xe6, 0x34, 0x15, 0x37, 0x3c, 0xb1, 0xee,
	0xc9, 0xe4, 0xf1, 0xc6, 0x11, 0xb2, 0xa3, 0x04, 0x74, 0xb3, 0xfd, 0xad, 0x7f, 0x17, 0xc0, 0xc8,
	0x97, 0xc9, 0x1e, 0x36, 0x2a, 0xc9, 0x24, 0x16, 0x51, 0xfe, 0xc1, 0x43, 0x76, 0x6b, 0x39, 0x69,
	0x31, 0xbd, 0x16, 0x37, 0x4f, 0xaf, 0xa5, 0x95, 0xe9, 0x75, 0x7d, 0xf8, 0x22, 0x50, 0x9e, 0xc5,
	0x3e, 0x16, 0x34, 0xb4, 0x83, 0x84, 0xc9, 0x77, 0xa0, 0xc9, 0x68, 0xca, 0xbd, 0xc5, 0x6c, 0x5d,
	0x91, 0xb3, 0x75, 0x03, 0xa9, 0xa3, 0x7c, 0xbe, 0xfe, 0x10, 0x76, 0xa4, 0xb9, 0x97, 0xf8, 0xaa,
	0x92, 0xaf, 0x29, 0xc9, 0x0b, 0xc6, 0xf7, 0xa0, 0xc1, 0x03, 0xb6, 0xc4, 0xa6, 0x06, 0xf9, 0x6d,
	0x1e, 0xb0, 0x9c, 0xa9, 0xb5, 0x07, 0xdb, 0xcb, 0x01, 0x9f, 0xa9, 0x5a, 0xc8, 0x55, 0x6d, 0xfd,
	0xb1, 0x00, 0xb0, 0x08, 0x64, 0x8c, 0x22, 0x1a, 0x45, 0xaa, 0x02, 0x29, 0xae, 0x2a, 0x8d, 0x22,
	0x59, 0x7e, 0xde, 0x85, 0x6d, 0x16, 0xde, 0x06, 0x7e, 0x48, 0x99, 0xb7, 0x48, 0x00, 0xf5, 0x8c,
	0xa6, 0x63, 0x30, 0x8f, 0x29, 0xdd, 0xe6, 0x87, 0x3a, 0xa2, 0x2c, 0xa8, 0x46, 0x74, 0xf2, 0x1c,
	0xbb, 0x5c, 0x65, 0xa8, 0x0c, 0xc5, 0xb2, 0x76, 0xcb, 0xc7, 0x72, 0x8f, 0x9e, 0x91, 0x6e, 0xf9,
	0xf8, 0x32, 0xf6, 0x5b, 0xbf, 0x2f, 0x40, 0xc5, 0xc9, 0x1f, 0xc5, 0xff, 0x4c, 0x2d, 0x1a, 0x45,
	0x3e, 0x17, 0x2c, 0x53, 0x4b, 0xa3, 0xa8, 0x96, 0x88, 0xe8, 0xb2, 0x5a, 0x22, 0xa2, 0x97, 0xb1,
	0xdf, 0xfe, 0x57, 0x11, 0x4a, 0x47, 0x82, 0xad, 0x35, 0x4b, 0xef, 0x80, 0xa1, 0x8a, 0xd8, 0xa2,
	0xb8, 0xd6, 0x14, 0xc1, 0x91, 0xe3, 0x7c, 0x14, 0x63, 0xb5, 0x52, 0xa1, 0xa3, 0x10, 0x8c, 0x13,
	0xca, 0xf4, 0xd1, 0x65, 0x57, 0xc2, 0xe4, 0xa7, 0x50, 0xcb, 0x02, 0x5f, 0x67, 0xc6, 0xc7, 0xaf,
	0x8c, 0x7b, 0x37, 0x67, 0x97, 0x63, 0x29, 0xa7, 0xbe, 0x60, 0x7a, 0x02, 0xd1, 0x98, 0x1c, 0x82,
	0xf5, 0x14, 0x89, 0x43, 0xb0, 0x60, 0xe4, 0x67, 0x50, 0xc7, 0x0a, 0x97, 0xa5, 0xfe, 0x9a, 0x4c,
	0xfd, 0x4f, 0x36, 0x15, 0x38, 0xfc, 0xd3, 0x15, 0xc0, 0x18, 0x67, 0x20, 0x9a, 0xed, 0xc5, 0x8c,
	0xfa, 0x38, 0x9f, 0x19, 0x72, 0xc8, 0xcb, 0x50, 0x79, 0x56, 0x1a, 0xcb, 0xe1, 0xa4, 0xe0, 0x22,
	0xd8, 0xee, 0x80, 0x91, 0xcb, 0x20, 0x0f, 0xe0, 0xfe, 0x91, 0xd3, 0xeb, 0xf4, 0xd6, 0x0a, 0xda,
	0x0e, 0xd4, 0x17, 0xf5, 0xaa, 0xa7, 0xfa, 0xaf, 0xde, 0xc5, 0x10, 0xe1, 0x62, 0xdb, 0xc6, 0x2e,
	0x97, 0xa6, 0x68, 0x75, 0xec, 0x0f, 0x58, 0xd6, 0x68, 0xed, 0x6e, 0x2c, 0xc9, 0xc8, 0x80, 0xa6,
	0x95, 0x5f, 0x12, 0x75, 0x99, 0x42, 0xb8, 0xfd, 0xab, 0x02, 0xd4, 0x65, 0x75, 0x4d, 0xa2, 0x30,
	0x48, 0xf8, 0xeb, 0xda, 0x9b, 0x4f, 0xa0, 0x86, 0xdb, 0xc6, 0x82, 0x65, 0x9f, 0x3d, 0xd7, 0x07,
	0x66, 0xad, 0x96, 0x9b, 0x73, 0xa2, 0x50, 0x1e, 0xc7, 0x61, 0xec, 0x4d, 0x42, 0xa6, 0xdc, 0x5d,
	0x76, 0x0d, 0x49, 0xe9, 0x86, 0x8c, 0xb7, 0x29, 0xec, 0xf6, 0x92, 0xa8, 0x8b, 0x59, 0xbb, 0x1f,
	0xa6, 0xe2, 0x99, 0x98, 0xd0, 0x2c, 0xe5, 0xb0, 0x24, 0xd2, 0x6a, 0x94, 0x5d, 0x85, 0xc8, 0x4f,
	0x75, 0x2a, 0xe3, 0xcf, 0xf2, 0xa0, 0x52, 0x35, 0xe0, 0x72, 0x26, 0xee, 0x88, 0xaa, 0x8f, 0x7e,
	0x27, 0xbf, 0x81, 0x66, 0xd3, 0xd1, 0x68, 0x70, 0x39, 0x72, 0x3a, 0x03, 0x6f, 0x83, 0xcd, 0x1f,
	0xc2, 0x5b, 0xd9, 0xea, 0xb1, 0x6d, 0xf7, 0xbc, 0xb3, 0xa1, 0x77, 0x86, 0x1e, 0x30, 0x0b, 0x9b,
	0x96, 0x2e, 0xce, 0x3b, 0x67, 0x67, 0x66, 0x91, 0xb4, 0xe0, 0xed, 0x95, 0xa5, 0xce, 0x30, 0xdb,
	0x56, 0xde, 0xb8, 0xa6, 0xf6, 0x95, 0xc8, 0x63, 0x78, 0x98, 0xad, 0xa9, 0x6f, 0x6d, 0x28, 0xf4,
	0xc4, 0xed, 0x0c, 0x4f, 0x9d, 0xae, 0xb9, 0xb5, 0xac, 0xea, 0x62, 0xf9, 0xa8, 0xd3, 0xef, 0xdb,
	0xae, 0x59, 0x21, 0xf7, 0x61, 0x67, 0x74, 0xd9, 0xe9, 0xff, 0xc2, 0xc9, 0xe5, 0x9a, 0xd5, 0x0d,
	0x12, 0xf1, 0x3c, 0xbd, 0xc7, 0x20, 0x7b, 0xf0, 0x68, 0x5d, 0xe2, 0xc8, 0xfe, 0x6a, 0xe4, 0x39,
	0xe7, 0x9d, 0x13, 0xdb, 0x84, 0x4d, 0xb7, 0x3c, 0x71, 0x07, 0x97, 0x43, 0xb3, 0x8e, 0x81, 0x9a,
	0x2d, 0x3d, 0x75, 0x7a, 0xf6, 0xc0, 0x1b, 0x76, 0x46, 0xdd, 0x53, 0x73, 0x9b, 0x10, 0x68, 0xf6,
	0xed, 0xd1, 0x97, 0x03, 0xf7, 0x0b, 0x4f, 0x7f, 0x48, 0x6c, 0x20, 0x2d, 0x63, 0xd6, 0xb4, 0xa6,
	0x1c, 0x18, 0x97, 0x34, 0xce, 0x6d, 0xbb, 0xb3, 0x61, 0x45, 0x99, 0xc8, 0xdc, 0xb0, 0xa2, 0xd4,
	0xb9, 0xb7, 0xd1, 0xb0, 0x6a, 0x8d, 0x90, 0x27, 0xd0, 0xca, 0xd6, 0xf2, 0x0f, 0x97, 0x0b, 0xa9,
	0xf7, 0xc7, 0x15, 0xf9, 0x4f, 0x80, 0x1f, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xf6, 0xca,
	0x40, 0x15, 0x18, 0x00, 0x00,
}
